#!/usr/bin/env python3
"""FastAPI chatbot with both a plain (non-streaming) and a streaming endpoint,
sharing one OpenAI client/pipeline.

Pipeline for both endpoints:
    Client -> FastAPI route -> Pydantic request model -> OpenAI chat completion
    -> Pydantic/plain-text response

Run:
    uvicorn api:app --reload --app-dir src

Then:
    # non-streaming: waits for the full answer, returns one JSON object
    curl -X POST http://127.0.0.1:8000/chat \
        -H "Content-Type: application/json" \
        -d '{"message": "Hello, who are you?"}'

    # streaming: returns the answer as it becomes available, word by word
    curl -N -X POST http://127.0.0.1:8000/ask \
        -H "Content-Type: application/json" \
        -d '{"question": "What is RAG?"}'

Interactive API docs (Swagger UI, auto-generated by FastAPI from the routes
and Pydantic models below):
    http://127.0.0.1:8000/docs   (Swagger UI)
    http://127.0.0.1:8000/redoc  (ReDoc)
"""
from __future__ import annotations

import asyncio
from collections.abc import AsyncGenerator

from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from openai import OpenAI, OpenAIError
from pydantic import BaseModel, ConfigDict

from config import load_settings

app = FastAPI(
    title="Agentic RAG Chatbot API",
    description=(
        "Learning example of an LLM-backed chatbot with both a "
        "non-streaming (`/chat`) and a streaming (`/ask`) endpoint."
    ),
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

settings = load_settings()
client = OpenAI(api_key=settings.openai_api_key)


class ChatRequest(BaseModel):
    model_config = ConfigDict(json_schema_extra={"example": {"message": "Hello, who are you?"}})

    message: str


class ChatResponse(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={"example": {"reply": "I'm a helpful assistant. How can I help?"}}
    )

    reply: str


class Question(BaseModel):
    model_config = ConfigDict(json_schema_extra={"example": {"question": "What is RAG?"}})

    question: str


def _generate_answer(prompt: str) -> str:
    """Shared pipeline step: one blocking call to the chat model, full answer back."""
    completion = client.chat.completions.create(
        model=settings.chat_model,
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt},
        ],
    )
    return completion.choices[0].message.content or ""


# --- Non-streaming: client waits, gets one complete JSON response -----------
@app.post(
    "/chat",
    response_model=ChatResponse,
    tags=["chat"],
    summary="Ask a question and get one complete answer",
    description="Blocks until the full LLM answer is generated, then returns it as a single JSON object.",
)
def chat(request: ChatRequest) -> ChatResponse:
    try:
        reply = _generate_answer(request.message)
    except OpenAIError as e:
        raise HTTPException(status_code=502, detail=str(e)) from e
    return ChatResponse(reply=reply)


# --- Streaming: client gets the answer incrementally, chunk by chunk --------
async def stream_answer(question: str) -> AsyncGenerator[str, None]:
    full_answer = _generate_answer(question)
    for word in full_answer.split(" "):
        yield word + " "
        await asyncio.sleep(0.05)  # simulate token-by-token streaming pace


@app.post(
    "/ask",
    tags=["chat"],
    summary="Ask a question and stream the answer chunk by chunk",
    description="Returns a `text/plain` streaming response; words arrive incrementally instead of all at once.",
)
def ask(request: Question) -> StreamingResponse:
    return StreamingResponse(stream_answer(request.question), media_type="text/plain")


@app.get("/health", tags=["health"], summary="Liveness check")
def health() -> dict[str, str]:
    return {"status": "ok"}
