#!/usr/bin/env python3
"""FastAPI chatbot with both a plain (non-streaming) and a streaming endpoint,
sharing one OpenAI client/pipeline.

Pipeline for both endpoints:
    Client -> FastAPI route -> Pydantic request model -> OpenAI chat completion
    -> Pydantic/plain-text response

Run:
    uvicorn api:app --reload --app-dir src

Then:
    # non-streaming: waits for the full answer, returns one JSON object
    curl -X POST http://127.0.0.1:8000/chat \
        -H "Content-Type: application/json" \
        -d '{"message": "Hello, who are you?"}'

    # streaming: returns the answer as it becomes available, word by word
    curl -N -X POST http://127.0.0.1:8000/ask \
        -H "Content-Type: application/json" \
        -d '{"question": "What is RAG?"}'

Interactive API docs (Swagger UI, auto-generated by FastAPI from the routes
and Pydantic models below):
    http://127.0.0.1:8000/docs   (Swagger UI)
    http://127.0.0.1:8000/redoc  (ReDoc)
"""
from __future__ import annotations

import asyncio
import json
from collections.abc import AsyncGenerator

from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from openai import OpenAI, OpenAIError
from openai.types.chat import ChatCompletion
from pydantic import BaseModel, ConfigDict, Field

from config import load_settings

app = FastAPI(
    title="Agentic RAG Chatbot API",
    description=(
        "Learning example of an LLM-backed chatbot with both a "
        "non-streaming (`/chat`) and a streaming (`/ask`) endpoint."
    ),
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

settings = load_settings()
client = OpenAI(api_key=settings.openai_api_key)

# USD per 1,000,000 tokens (standard tier). Snapshot from
# https://developers.openai.com/api/docs/pricing -- re-check before relying
# on this for real billing decisions. Unknown models fall back to None.
MODEL_PRICING: dict[str, tuple[float, float]] = {
    "gpt-4o-mini": (0.15, 0.60),
    "gpt-4o": (2.50, 10.00),
    "gpt-4.1": (2.00, 8.00),
    "gpt-4.1-mini": (0.40, 1.60),
    "gpt-4.1-nano": (0.10, 0.40),
    "gpt-5": (1.25, 10.00),
    "gpt-5-mini": (0.25, 2.00),
    "gpt-5-nano": (0.05, 0.40),
    "gpt-3.5-turbo": (0.50, 1.50),
}

# Appended after the streamed answer text, so the client can split the
# visible answer from the trailing cost metadata.
COST_META_MARKER = "\x00COST_META\x00"


class ChatRequest(BaseModel):
    model_config = ConfigDict(json_schema_extra={"example": {"message": "Hello, who are you?"}})

    message: str


class ChatResponse(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "reply": "I'm a helpful assistant. How can I help?",
                "model": "gpt-4o-mini",
                "prompt_tokens": 12,
                "completion_tokens": 9,
                "cost_usd": 0.0000072,
            }
        }
    )

    reply: str
    model: str
    prompt_tokens: int
    completion_tokens: int
    cost_usd: float | None


class Question(BaseModel):
    model_config = ConfigDict(json_schema_extra={"example": {"question": "What is RAG?"}})

    question: str


# Structured answer shape, enforced via tool calling below. Because the tool's
# argument schema and the response_model are the SAME Pydantic model, the
# contract the LLM must fill and the contract FastAPI publishes in
# /openapi.json can never drift apart.
class AnswerPayload(BaseModel):
    content: str
    confidence: float = Field(ge=0.0, le=1.0)
    sources: list[str] = []


ANSWER_TOOL_NAME = "submit_answer"
ANSWER_TOOL = {
    "type": "function",
    "function": {
        "name": ANSWER_TOOL_NAME,
        "description": "Submit the final structured answer to the user's question.",
        "parameters": AnswerPayload.model_json_schema(),
    },
}


class StructuredChatResponse(BaseModel):
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "answer": {
                    "content": "RAG combines retrieval with generation.",
                    "confidence": 0.95,
                    "sources": [],
                },
                "model": "gpt-4o-mini",
                "prompt_tokens": 30,
                "completion_tokens": 20,
                "cost_usd": 0.0000165,
            }
        }
    )

    answer: AnswerPayload
    model: str
    prompt_tokens: int
    completion_tokens: int
    cost_usd: float | None


def _estimate_cost(model: str, prompt_tokens: int, completion_tokens: int) -> float | None:
    """USD cost from actual token usage; None if model isn't in MODEL_PRICING."""
    rates = MODEL_PRICING.get(model)
    if rates is None:
        # dated snapshots like "gpt-4o-mini-2024-07-18" aren't literal keys;
        # match the longest known model name that prefixes the snapshot.
        for name in sorted(MODEL_PRICING, key=len, reverse=True):
            if model.startswith(name):
                rates = MODEL_PRICING[name]
                break
    if rates is None:
        return None
    input_rate, output_rate = rates
    return prompt_tokens / 1_000_000 * input_rate + completion_tokens / 1_000_000 * output_rate


def _generate_completion(prompt: str) -> ChatCompletion:
    """Shared pipeline step: one blocking call to the chat model, usage included."""
    return client.chat.completions.create(
        model=settings.chat_model,
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": prompt},
        ],
    )


def _generate_structured_completion(prompt: str) -> ChatCompletion:
    """Force the model to reply via the submit_answer tool call, not free text."""
    return client.chat.completions.create(
        model=settings.chat_model,
        messages=[
            {"role": "system", "content": "You are a helpful assistant. Always answer by calling submit_answer."},
            {"role": "user", "content": prompt},
        ],
        tools=[ANSWER_TOOL],
        tool_choice={"type": "function", "function": {"name": ANSWER_TOOL_NAME}},
    )


# --- Non-streaming: client waits, gets one complete JSON response -----------
@app.post(
    "/chat",
    response_model=ChatResponse,
    tags=["chat"],
    summary="Ask a question and get one complete answer",
    description="Blocks until the full LLM answer is generated, then returns it as a single JSON object.",
)
def chat(request: ChatRequest) -> ChatResponse:
    try:
        completion = _generate_completion(request.message)
    except OpenAIError as e:
        raise HTTPException(status_code=502, detail=str(e)) from e
    usage = completion.usage
    prompt_tokens = usage.prompt_tokens if usage else 0
    completion_tokens = usage.completion_tokens if usage else 0
    return ChatResponse(
        reply=completion.choices[0].message.content or "",
        model=completion.model,
        prompt_tokens=prompt_tokens,
        completion_tokens=completion_tokens,
        cost_usd=_estimate_cost(completion.model, prompt_tokens, completion_tokens),
    )


# --- Streaming: client gets the answer incrementally, chunk by chunk --------
async def stream_answer(question: str) -> AsyncGenerator[str, None]:
    completion = _generate_completion(question)
    full_answer = completion.choices[0].message.content or ""
    for word in full_answer.split(" "):
        yield word + " "
        await asyncio.sleep(0.05)  # simulate token-by-token streaming pace

    usage = completion.usage
    prompt_tokens = usage.prompt_tokens if usage else 0
    completion_tokens = usage.completion_tokens if usage else 0
    meta = {
        "model": completion.model,
        "prompt_tokens": prompt_tokens,
        "completion_tokens": completion_tokens,
        "cost_usd": _estimate_cost(completion.model, prompt_tokens, completion_tokens),
    }
    yield COST_META_MARKER + json.dumps(meta)


@app.post(
    "/ask",
    tags=["chat"],
    summary="Ask a question and stream the answer chunk by chunk",
    description="Returns a `text/plain` streaming response; words arrive incrementally instead of all at once.",
)
def ask(request: Question) -> StreamingResponse:
    return StreamingResponse(stream_answer(request.question), media_type="text/plain")


# --- Structured: tool calling enforces the AnswerPayload shape --------------
@app.post(
    "/chat/structured",
    response_model=StructuredChatResponse,
    tags=["chat"],
    summary="Ask a question and get a schema-enforced structured answer",
    description=(
        "Uses OpenAI tool calling to force the reply into the AnswerPayload shape "
        "(content, confidence, sources) -- the exact same Pydantic model documented "
        "for this response in /openapi.json, so the LLM output and the published "
        "API contract can't drift apart."
    ),
)
def chat_structured(request: ChatRequest) -> StructuredChatResponse:
    try:
        completion = _generate_structured_completion(request.message)
    except OpenAIError as e:
        raise HTTPException(status_code=502, detail=str(e)) from e

    tool_calls = completion.choices[0].message.tool_calls
    if not tool_calls:
        raise HTTPException(status_code=502, detail="model did not call submit_answer")
    answer = AnswerPayload.model_validate_json(tool_calls[0].function.arguments)

    usage = completion.usage
    prompt_tokens = usage.prompt_tokens if usage else 0
    completion_tokens = usage.completion_tokens if usage else 0
    return StructuredChatResponse(
        answer=answer,
        model=completion.model,
        prompt_tokens=prompt_tokens,
        completion_tokens=completion_tokens,
        cost_usd=_estimate_cost(completion.model, prompt_tokens, completion_tokens),
    )


@app.get("/health", tags=["health"], summary="Liveness check")
def health() -> dict[str, str]:
    return {"status": "ok"}
